name: Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { dir: healthcarepackaging.com, stack: tauron, id: 5d88cef7f175132c008b456f, account: pmmi, tenant: pmmi_all, rancher_label: pmmi-media-group-healthcarepackaging.com }
          - { dir: mundopmmi.com, stack: tauron, id: 5d0a748572c1aa35008b4567, account: pmmi, tenant: pmmi_mundo, rancher_label: pmmi-media-group-mundopmmi.com }
          - { dir: oemmagazine.org, stack: tauron, id: 5d88cf05f175132c008b4573, account: pmmi, tenant: pmmi_all, rancher_label: pmmi-media-group-oemmagazine.org }
          - { dir: packworld.com, stack: tauron, id: 5d88cedef175132c008b456b, account: pmmi, tenant: pmmi_all, rancher_label: pmmi-media-group-packworld.com }
          - { dir: profoodworld.com, stack: tauron, id: 5d88cf1af175132c008b4577, account: pmmi, tenant: pmmi_all, rancher_label: pmmi-media-group-profoodworld.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      docker_image: website-${{ matrix.site.dir }}
      site_host: ${{ matrix.site.dir }}
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
